version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: suar_postgres
    restart: always
    environment:
      POSTGRES_USER: suar_user
      POSTGRES_PASSWORD: suar_password
      POSTGRES_DB: suar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
