name: Sync Backend to Hugging Face Spaces

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only trigger when changes are made inside backend/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history is required for git subtree split

      - name: Push Subdirectory to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure Git credentials
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Create a fresh clean git repository for backend directory to avoid pushing old commit history blobs > 10MB
          cd backend
          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy latest backend snapshot to Hugging Face Spaces"

          # Force push clean HEAD snapshot to Hugging Face Spaces main branch
          git push -f https://lintangnv:$HF_TOKEN@huggingface.co/spaces/lintangnv/suar-backend HEAD:refs/heads/main
